### ISSUE TITLE
Signup form broken?

### ISSUE THREAD

**Issue by zbskii** [engmanagers/engmanagers.github.io#16]
Hey! I've applied for membership a couple of times and haven't heard anything back. Is the google form working?

**Comment by irrg** [comment]
Same here. The site is very light on actual contact info, as well…

**Comment by stebennett** [comment]
Hey - Apologies for this. I got a bit behind with processing invites.

**Comment by dmyers** [comment]
I also filed it out recently @stebennett and would love to join if possible.
