### ISSUE TITLE
Add unsolicited advice guidance to code of conduct

### ISSUE THREAD

**Issue by stebennett** [engmanagers/engmanagers.github.io#3]
The engineering managers Slack team promotes the well-being of it's members through the creation of a safe and collaborative environment to discuss problems.

At times, it's also a useful place to vent, rant or just get something of your chest about a situation that you find yourself in. In these cases (and in many others) the person is often looking for a place for their frustrations to be heard. They are not always looking for advice or solutions to their situation. 

The most common response to hearing someone else's problems is to try and help. It's a noble intention, but in circumstances where help hasn't been explicitly sought, the advice can come across as a patronising approach to the person and their problems. Providing explanations to underrepresented groups from a position of privilege can have the same effect.

I propose that we add wording to the code of conduct to make it explicit that unsolicited advice and privileged explaining are not welcome in the Slack team.

Related links:

- http://www.huffingtonpost.com/sezin-koehler/why-i-stopped-giving-unsolicited-advice_b_7985278.html
- http://everydayfeminism.com/2014/12/the-problem-with-privilege-explaining/

**Comment by jillwetzler** [comment]
@steve-codes I tend to fall back on the Gestalt Protocol, unless someone has specifically asked me for advice (and even then I'll still tend towards Gestalt). This is the best overview I've seen of it: http://www.stathakis.com/blog/leadership/bid/320702/What-is-Gestalt-and-Why-You-Need-To-Know-It

We should default to speaking from our own experiences if we can identify with a problem. Allow people to draw their own conclusions from our experiences and decide how it translates to their situation.

**Comment by stebennett** [comment]
@jillwetzler Thanks for that. Nice summary. Do you think it'd be good to modify the CoC to reference the Gestalt Protocol?

**Comment by jillwetzler** [comment]
Yep that's why I suggested it! :) Do you want to do the wordsmithing?
