### ISSUE TITLE
Add reference to Chatham House Rule to the CoC

### ISSUE THREAD

**Issue by stebennett** [engmanagers/engmanagers.github.io#5]
It's been mentioned a couple of times in the Slack team that we should operate under Chatham House Rule. This is currently missing from the code of conduct, so it should be added.

Defn: a rule or principle according to which information disclosed during a meeting may be reported by those present, but the source of that information may not be explicitly or implicitly identified.

**Comment by mmzyk** [comment]
Looks good. My only thought is that it might be worth calling out on it's own line so it's more noticeable. Being at the end of a paragraph that is giving definitions not related to this makes this feel tacked on and causes it to lose some weight.

**Comment by stebennett** [comment]
@mmzyk Great suggestion. Moved to a new paragraph.
